name: Mirror
on: [push]
jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to Sourcehut
      env:
        GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
        SSH_PRIVATE_KEY: ${{ secrets.SOURCEHUT_SSH_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git remote add mirror git@git.sr.ht:~harmless/security.txt
        git push -u --tags --force --prune -u mirror